cacheFolder: ./.yarn/cache

defaultLanguageName: node

defaultProtocol: "npm:"

enableColors: true

enableGlobalCache: false

enableHyperlinks: true

enableInlineBuilds: true

enableProgressBars: true

logFilters:
  - code: YN0000
    level: info
  - code: YN0007
    level: info
  - code: YN0013
    level: info
  - code: YN0032
    level: info
  - code: YN0060
    level: info
  - code: YN0061
    level: info

nmHoistingLimits: workspaces

nmSelfReferences: true

nodeLinker: node-modules

npmAlwaysAuth: true

npmPublishAccess: restricted

npmPublishRegistry: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-envinfo.cjs
    spec: "https://unpkg.com/yarn-plugin-envinfo"

pnpFallbackMode: all

pnpMode: strict

preferInteractive: true
